### ISSUE TITLE
Tab width not resizing to the maximum of the window - Vim Like Tab + Paner Package

### ISSUE THREAD

**Issue by err0x1a** [Kesin11/atom-vim-like-tab#9]
Thanks for bringing this Vim feature to Atom.

I'm having trouble working with the [Paner package](https://github.com/t9md/atom-paner) and this package. But I do not know which package is the problem.

Can you check the attached images? I think it was easier to explain than with text.

![01](https://user-images.githubusercontent.com/324835/35335117-b4264dc4-00fb-11e8-985a-d2d179a3b4e0.png)
![02](https://user-images.githubusercontent.com/324835/35335123-b8efc326-00fb-11e8-815a-21c325f36f2f.png)

**Comment by Kesin11** [comment]
I think it caused by atom-vim-like-tab.
Because atom-vim-like-tab can't open pane in a correct position when split horizontal in first tab.
You can see it with follow steps.

1. Split pane 2x2 in first tab.
2. Execute `Atom Vim Like Tab: New`
3. Open some file in second tab.

It's a bug. But I couldn't fix it when I tackled it in a year ago.
atom-vim-like-tab manipulate panes DOM for realize Vim like tab and extend editor view virtually.
Unfortunately also Atom will manipulating panes DOM when user split pane horizontally, as a result above bug will occur.

If you could fix it, I'm welcome to your pull request 😄

**Comment by err0x1a** [comment]
All right, I will see if I can give a try.

Thanks anyway!
